/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Order {
  'id' : bigint,
  'status' : string,
  'userId' : Principal,
  'createdAt' : bigint,
  'shippingAddress' : ShippingAddress,
  'items' : Array<OrderItem>,
  'totalPrice' : number,
}
export interface OrderItem {
  'name' : string,
  'productId' : bigint,
  'quantity' : bigint,
  'price' : number,
}
export interface Product {
  'id' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'numReviews' : bigint,
  'description' : string,
  'stock' : bigint,
  'imageUrl' : string,
  'category' : string,
  'rating' : number,
  'price' : number,
}
export interface ProductInput {
  'name' : string,
  'description' : string,
  'stock' : bigint,
  'imageUrl' : string,
  'category' : string,
  'price' : number,
}
export interface Review {
  'id' : bigint,
  'userName' : string,
  'userId' : Principal,
  'createdAt' : bigint,
  'productId' : bigint,
  'comment' : string,
  'rating' : bigint,
}
export interface ShippingAddress {
  'zip' : string,
  'street' : string,
  'country' : string,
  'city' : string,
  'state' : string,
}
export interface UserProfile { 'name' : string, 'email' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addReview' : ActorMethod<[bigint, bigint, string, string], undefined>,
  'addToCart' : ActorMethod<[bigint, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearCart' : ActorMethod<[], undefined>,
  'createProduct' : ActorMethod<[ProductInput], bigint>,
  'deleteProduct' : ActorMethod<[bigint], undefined>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCart' : ActorMethod<
    [],
    Array<{ 'productId' : bigint, 'quantity' : bigint }>
  >,
  'getMyOrders' : ActorMethod<[], Array<Order>>,
  'getOrder' : ActorMethod<[bigint], Order>,
  'getProduct' : ActorMethod<[bigint], Product>,
  'getProductReviews' : ActorMethod<[bigint], Array<Review>>,
  'getProductsByCategory' : ActorMethod<[string], Array<Product>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'placeOrder' : ActorMethod<
    [Array<OrderItem>, number, ShippingAddress],
    bigint
  >,
  'removeFromCart' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchProducts' : ActorMethod<[string], Array<Product>>,
  'sortProductsByPrice' : ActorMethod<[], Array<Product>>,
  'sortProductsByRating' : ActorMethod<[], Array<Product>>,
  'updateCartQuantity' : ActorMethod<[bigint, bigint], undefined>,
  'updateOrderStatus' : ActorMethod<[bigint, string], undefined>,
  'updateProduct' : ActorMethod<[bigint, ProductInput], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];